title: Code By Zain
description: > # this means to ignore newlines until "baseurl:"
  Welcome to Zain Siddiqui's onlune portfolio
permalink: ':title/'
baseurl: "/portfolio" # the subpath of your site, e.g. /blog
url: "https://codebyzain.com" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Zain Siddiqui # add your name
author-img: david-freeman.jpg # add your photo
about-author: I am a UCI student graduating in March 2021 and have a knack for full stack web development. # add description
social-twitter: zainyydoe # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: zasiddiq # add your Github handle
social-linkedin: zasiddiq # add your Linkedin handle
social-email: zainsiddiquica@gmail.com # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
